### ISSUE TITLE
Data variables don't store all the right values (at least `archive_cases_dv_subset`)

### ISSUE THREAD

**Issue by kenmawer** [cmu-delphi/epiprocess#150] opened 2022-07-19 20:15 UTC
`archive_cases_dv_subset` behaves differently from `as_epi_archive(archive_cases_dv_subset$DT)`, as the former does not have column names defined, as noted by what shows up when calling (i.e. printing) the objects. I suspect that other data objects have similar problems, too.

Note: this may be related to or even a duplicate of #125; I still need to confirm that this is the case though.

**Comment by brookslogan** [comment] 2022-07-22 16:56
Even with the fix for #125 included in #111, this will still be different, as I have kept `archive_cases_dv_subet` uncompactified to not break some tests, and the latter expression will compactify+warn.  We should sometime make the tests not dependent on this data object so we are free to compactify=TRUE in the data object generation + do other changes to the data object without impacting the tests.

**Comment by kenmawer** [comment] 2022-07-22 17:20
For this, I assumed as though this doesn't use compactify.

**Comment by brookslogan** [comment] 2022-07-25 08:58
Okay, then I believe this is a consequence of #125 and resolved by changes that are included in #101.  Marking as duplicate of #125, closing.

**Closed by brookslogan** 2022-07-25 08:58 UTC
Labels: bug, duplicate, P1
