### ISSUE TITLE
Visualizations for maps, etc.

### ISSUE THREAD

**Issue by kenmawer** [cmu-delphi/epiprocess#169] opened 2022-07-26 21:05 UTC
During an earlier meeting, we discussed about adding visualization features onto our R packages, such as having a plot that uses US states to create a coloured USA map. However, we do not intend to integrate this with more advanced visualization software such as Tableau or Power BI.

This issue will be updated depending on what types of visualizations should be added.

**Comment by brookslogan** [comment] 2022-08-01 01:36
Closing this as a duplicate of #2 as a generic plotting issue.  Please re-open and clarify if it's supposed to serve a different purpose.  We might want to spin out specific issues for specific types of plots we decide to add, after resolving the questions raised in #2 about where these should belong.

**Closed by brookslogan** 2022-08-01 01:36 UTC
Labels: duplicate, enhancement
