### ISSUE TITLE
Improve checking for out of bound `ref_time_values` when using `epi_slide`.

### ISSUE THREAD

**Issue by kenmawer** [cmu-delphi/epiprocess#206] opened 2022-08-16 00:05 UTC
Currently, an error is thrown only if ALL `ref_time_values` are out of bounds. If this value is contained, but other values within bounds are contained, the out of bound value is omitted, with the values within bounds being used for the `epi_slide`.

**Comment by dshemetov** [comment] 2024-10-15 07:16
Closing as outdated. This behavior is as intended.

**Closed by dshemetov** 2024-10-15 07:16 UTC

**Comment by brookslogan** [comment] 2024-10-15 09:22
(The behavior described here wasn't intended, but it's already been replaced with more sane behavior: requiring that all `ref_time_values` appear as `time_values` to proceed, rather than requiring all to be out of bounds to be an error.)
